# Generated by Django 6.1 on 2026-09-17 19:02

import apps.courses.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_rename_file_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='content',
            field=apps.courses.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=apps.courses.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
